workflows:
  guuri-android-workflow:
    name: GUURI Android Build
    max_build_duration: 60
    instance_type: mac_mini_m2
    environment:
      flutter: stable
      vars:
        PACKAGE_NAME: "com.guuri.app"
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: main
          include: true
    scripts:
      - name: Get Flutter packages
        script: |
          flutter pub get
      - name: Build APK
        script: |
          flutter build apk --release
    artifacts:
      - build/**/outputs/**/*.apk
    publishing:
      email:
        recipients:
        - asad510091@gmail.com
        
        notify:
          success: true
          failure: true
